{
    "openapi": "3.0.0",
    "info": {
        "title": "API Ignite-SOLID",
        "description": "Essa é a documentação da API Ignite-SOLID, que tem como objetivo o gerenciamento de usuários de um banco em memória",
        "contact": {
            "email": "pabloxt14@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333",
            "description": "API de teste"
        }
    ],
    "tags": [
        {
            "name": "users",
            "description": "Gerenciamento de usuários"
        }
    ],
    "paths": {
        "/users": {
            "post": {
                "tags": ["users"],
                "summary": "Cadastro de usuário",
                "description": "Essa rota será responsável por cadastrar um novo usuário",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "John Doe",
                                    "email": "johndoe@gmail.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "This email is already in use!"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": ["users"],
                "summary": "Retorna todos os usuários",
                "description": "Somente usuário admin pode acessar.",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "header",
                        "description": "ID do usuário admin",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "example": [
                                        {
                                            "admin": false,
                                            "id": "cc5359f3-35fa-4c51-b02b-88a2df2ef0aa",
                                            "name": "John Doe 1",
                                            "email": "johndoe1@gmail.com",
                                            "created_at": "2022-07-12T21:20:11.060Z",
                                            "updated_at": "2022-07-12T21:20:11.060Z" 
                                        },
                                        {
                                            "admin": true,
                                            "id": "ff5359f3-35fa-4c51-b02b-88a2df2ef0aa",
                                            "name": "John Doe 2",
                                            "email": "johndoe2@gmail.com",
                                            "created_at": "2022-07-12T21:20:11.060Z",
                                            "updated_at": "2022-07-12T21:20:11.060Z" 
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "You need to be an administrator to list all users."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "tags": ["users"],
                "summary": "Retorna um usuário específico",
                "description": "Essa rota é responsável por retornar um usuário específico por id.",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ID do usuário",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "User not found!"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}/admin": {
            "patch": {
                "tags": ["users"],
                "summary": "Tornar usuário em admin",
                "description": "Essa rota será responsável por tornar o usuário em admin",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ID do usuário para tornar em admin",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/UserAdmin"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "error": "User not found!"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "User": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "admin": {
                        "type": "boolean"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "example": {                                                        
                    "admin": false,
                    "id": "cc5359f3-35fa-4c51-b02b-88a2df2ef0aa",
                    "name": "John Doe",
                    "email": "johndoe@gmail.com",
                    "created_at": "2022-07-12T21:20:11.060Z",
                    "updated_at": "2022-07-12T21:20:11.060Z"                                             
                }
            },
            "UserAdmin": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "admin": {
                        "type": "boolean"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    }
                },
                "example": {                                                        
                    "admin": true,
                    "id": "cc5359f3-35fa-4c51-b02b-88a2df2ef0aa",
                    "name": "John Doe",
                    "email": "johndoe@gmail.com",
                    "created_at": "2022-07-12T21:20:11.060Z",
                    "updated_at": "2022-07-12T21:20:11.060Z"                                             
                }
            }
        }
    }
}